// <auto-generated />
namespace Hozio.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class preclientCtrl00 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(preclientCtrl00));
        
        string IMigrationMetadata.Id
        {
            get { return "202202052031230_pre-clientCtrl00"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
