// <auto-generated />
namespace Hozio.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class HOG2ModelAdds00 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(HOG2ModelAdds00));
        
        string IMigrationMetadata.Id
        {
            get { return "202202091931266_HOG2ModelAdds00"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
